### PR TITLE
Output empty tibble if no matching regions present (#236)

### LINKED ISSUE #236: `target_market_share()` gives informative message if no regional definitions match
Currnetly, when you input a `region_isos` argument to `target_market_share` that doesn't define any of the necessary regions in `scenario`, the error message is confusing and difficult to interpret. 

I would rather output an empty tibble, along with an informative message explaining what went wrong. 

---

Brief description of the problem

``` r
library(r2dii.data)
library(r2dii.analysis)

matched <- tibble::tribble(
  ~id_loan, ~loan_size_outstanding, ~loan_size_outstanding_currency, ~loan_size_credit_limit, ~loan_size_credit_limit_currency, ~id_2dii,            ~level, ~score,      ~sector,      ~name_ald,  ~sector_ald,
  "L162",                      1,                           "EUR",                       2,                            "EUR",    "UP1", "ultimate_parent",      1, "automotive", "shaanxi auto", "automotive"
)

ald <- tibble::tribble(
  ~name_company,      ~sector, ~technology, ~year, ~production, ~emission_factor, ~plant_location, ~is_ultimate_owner,
  "shaanxi auto", "automotive",       "ice",  2025,           1,                1,            "BF",               TRUE
)

scenario <- tibble::tribble(
  ~scenario,      ~sector, ~technology,  ~region, ~year, ~tmsr, ~smsp, ~scenario_source,
  "sds", "automotive",       "ice", "global",  2025,   0.5, -0.08,      "demo_2020"
)

# outputs fine if the demo region_isos is used
target_market_share(matched, ald, scenario, region_isos_demo)
#> # A tibble: 3 x 8
#>   sector technology  year region scenario_source metric production
#>   <chr>  <chr>      <dbl> <chr>  <chr>           <chr>       <dbl>
#> 1 autom… ice         2025 global demo_2020       proje…        1  
#> 2 autom… ice         2025 global demo_2020       corpo…        1  
#> 3 autom… ice         2025 global demo_2020       targe…        0.5
#> # … with 1 more variable: technology_share <dbl>

# but gives confusing error if you accidentally use the (wrong) default region_isos
target_market_share(
  matched, 
  ald, 
  scenario, 
  region_isos = r2dii.data::region_isos
)
#> Warning: Joining `region_isos` outputs 0 rows.
#> Error: Assigned data `vec_repeat(names(values_from), each = vec_size(row_ids))` must be compatible with existing data.
#> x Existing data has 2 rows.
#> x Assigned data has 0 rows.
#> ℹ Only vectors of size 1 are recycled.
```

<sup>Created on 2020-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

### PR DESCRIPTION
**Pull request by jdhoffa**
Closes #236

### CODE REVIEW

File: tests/testthat/test-target_market_share.R [hunk 1]
```diff
@@ -468,3 +468,28 @@ test_that("w/ some region missing some scenario outputs expected `production`
   expect_equal(target_sds$global$production, 0.5)
   expect_equal(target_sds$`non opec`$production, 0.5)
 })
+
+test_that("w/ no matching regions, outputs empty named tibble", {
+
```
Comment (maurolepore) [inline tests/testthat/test-target_market_share.R:473]: Nit: This spaces will be gone once we pass the styler. But it's nice to not have them in the first place.

**Review by maurolepore — APPROVED** [review]
LGTM.
I fixed two merge conflicts and the result is this: https://github.com/2DegreesInvesting/r2dii.analysis/pull/238/commits/79ac6351391c60f15ae632d89d620e3c4ea6162a

If this looks as you expected, then go ahead and merge.

**Comment by jdhoffa** [comment]
Yup this all looks good!
