### PR TITLE
Fix unweighted company

### LINKED ISSUE #239: Company level results projected error
The company-level results 

Company_results <- target_market_share(validated_matches, ald, scen, by_company = TRUE, weight_production = FALSE)

does not equal the projected (unweighted) values in the ALD for a given year, technology and company when there are multiple loans to the same company. 
If there is only one loan to the company in the loan book then the company results "projected" = the ALD production as expected.
 
This makes me think that despite the "weighted_production = FLASE" it is still weighting the results.

Loan book with 1 loan to each company - company-level results as expected 
[mock_lbk_1_loan.xlsx](https://github.com/2DegreesInvesting/r2dii.analysis/files/5623048/mock_lbk_1_loan.xlsx)

Loan book with multiple loans to each company - company-level results incorrect 
[mock_lbk_multi_loan.xlsx](https://github.com/2DegreesInvesting/r2dii.analysis/files/5623049/mock_lbk_multi_loan.xlsx)

### PR DESCRIPTION
**Pull request by jdhoffa**
`summarize_unweighted_production` now drops the crucial column `id_loan` and selects distinct values, to avoid erroneous double-counting when calculating the `unweighted` company production. 

Closes #239

### CODE REVIEW

File: tests/testthat/test-target_market_share.R [hunk 1]
```diff
@@ -521,3 +521,24 @@ test_that("w/ technology in ald but not loanbook, outputs all techs (#235)", {
   expect_equal(corporate_economy$ice$technology_share, 0.25)
   expect_equal(corporate_economy$electric$technology_share, 0.75)
 })
+
+test_that("w/ unweighted company flags & multi loans, outputs correctly (#239)", {
+  matched <- fake_matched(id_loan = c("L1", "L2"))
+
+  ald <- fake_ald()
+
+  scenario <- fake_scenario()
```
Comment (maurolepore) [inline tests/testthat/test-target_market_share.R:530]: Nit: I think these three statements belong to the same "initialization paragraph" (a common pattern in tests is to divde the code in three paragraphs -- initialization, computation, expectation). I would use not white line between them.

**Review by maurolepore — APPROVED** [review]
LGTM

File: tests/testthat/test-target_market_share.R (hunk 1 above)
Comment (jdhoffa) [reply tests/testthat/test-target_market_share.R:530]: sounds good and agreed! do you have a resource that explains the pattern of test division?

Comment (maurolepore) [reply tests/testthat/test-target_market_share.R]: Pretty sure it's in "Clean code". I have a hard copy here ... I'll see if I can find it.
