### PR TITLE
`target_sda` now outputs unweighted `emission_factor` by default, if `by_company = TRUE`

### LINKED ISSUE #376: Target_sda - Company level results wrong as they are loan weighted
In the target_sda function, there is no argument for Weight_production. (in the same way that there is for target_market_share) 

This means that when by_company is set to = TRUE the companies emission factors are weighted by their loan size. 
 
We want to be able to have the absolute (non-weighted) emission factors of companies when assessing at the company level. 

Hence the argument "weight_production" needs to be added to the function "target_sda"

furthermore, if Weight_production = TRUE - a warning message should be shown (i.e. the same one that is shown in the case of target_market_share)

### PR DESCRIPTION
**Pull request by jdhoffa**
Now:
* `target_sda(..., by_company = FALSE)` will calculate the loan-weighted emission factors, and aggregate them to portfolio level
* `target_sda(..., by_company = TRUE)` will output unweighted emission factors, and output them at company level

Note that the function `target_market_share()` has the argument `weight_production` which allows the user to manually control this behavior. I have elected not to include an analogous `weight_emission_factor` argument in this function, as the weighted but un-aggregated `emission_factor` value is not really interpretable or useful for the user, and would likely just cause confusion. 

Closes #376

### CODE REVIEW

File: R/summarize_weighted_production.R [hunk 1]
```diff
@@ -179,6 +179,19 @@ summarize_weighted_emission_factor <- function(data, ..., use_credit_limit = FAL
...
+summarize_unweighted_emission_factor <- function(data, ...) {
+  data <- data %>%
+    select(-c(
+      .data$id_loan,
+      .data$loan_size_credit_limit,
+      .data$loan_size_outstanding
+    )) %>%
+    distinct() %>%
+    group_by(.data$sector_ald, .data$year, ...) %>%
+    summarize(emission_factor_projected = mean(.data$emission_factor)) %>%
```
Comment (cjyetman) [inline R/summarize_weighted_production.R:191]: nit: you can use `.groups = "drop"` in `summarise()` and skip the `ungroup()`

File: tests/testthat/test-target_market_share.R [hunk 2]
```diff
@@ -488,7 +488,7 @@ test_that("w/ known input, outputs `technology_share` as expected (#184, #262)",
     c(0.6875, 0.3125)
   )
 
-  FIXME <- 1e-2  # Do we need 1e-3?
+  FIXME <- 1e-2 # Do we need 1e-3?
```
Comment (cjyetman) [inline tests/testthat/test-target_market_share.R:491]: nit: would rather see a useful function name and use FIXME in a comment

**Review by cjyetman — APPROVED** [review]
seems fine syntactically... left a few minor comments

File: R/summarize_weighted_production.R (hunk 1 above)
Comment (jdhoffa) [reply R/summarize_weighted_production.R:191]: Thank you, I actually prefer to call `ungroup()` explicitly (for totally aesthetic reasons).
Personally, I find it much easier to look through a dplyr chain for matching `group_by()` and `ungroup()` calls, than to look for a `.groups = "drop"` nested in a function call.

File: tests/testthat/test-target_market_share.R (hunk 2 above)
Comment (jdhoffa) [reply tests/testthat/test-target_market_share.R]: Will address this also in a separate PR

File: R/summarize_weighted_production.R (hunk 1 above)
Comment (cjyetman) [reply R/summarize_weighted_production.R:191]: fair enough, and agree it's easier to glance and pair up a `group_by()` with a `ungroup()`.... I kind of wish there were a `by` argument in `summarise()` so you could do something like...
```
data %>%
  summarise(emission_factor_projected = mean(.data$emission_factor), by = c(sector_ald, year))
```
instead of...
```
data %>%
  group_by(sector_ald, year, ...) %>%
  summarise(emission_factor_projected = mean(emission_factor)) %>%
  ungroup()
```
