### PR TITLE
`target_market_share` errors if input `data` has unexpected columns

### LINKED ISSUE #267: Company results - blank column
The company-level results are being outputed incorrectly when the "match_file" (input file for r2dii.match::priotization) has a blank column in it with **no header.** 

I can not reproduce this in a reprex so the one attached below is incomplete. 
The error can, however, be recreated if you use the attached csv file. 
Note if you delete the blank column in the attached file within R then the expected = the actual 

Apologies that I cant recreate this - I really can't get my head around it. 
Either way, I have attached the reprex here, which doesn't work.  but it may be helpful to understand what I have done. 
you will see expected = actual 
but if you use the attached csv in place of "match_file" then expected will != actual
(please let me know if this is unclear and/or if you work out why)

reprex

```r
#load required packages and files
library(tidyverse)
#> Warning: package 'tidyverse' was built under R version 4.0.3
library(r2dii.analysis)
library(r2dii.data)
#> Warning: package 'r2dii.data' was built under R version 4.0.3
library(r2dii.match)
#> Warning: package 'r2dii.match' was built under R version 4.0.3
devtools::install_github("2DegreesInvesting/r2dii.analysis")
#> WARNING: Rtools is required to build R packages, but is not currently installed.
#> 
#> Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/.
#> Using github PAT from envvar GITHUB_PAT
#> Skipping install of 'r2dii.analysis' from a github remote, the SHA1 (279459dd) has not changed since last install.
#>   Use `force = TRUE` to force installation

# load scenario file

scenario <- r2dii.data::scenario_demo_2020
scenario <- scenario %>% mutate(scenario_source = "weo_2019")

# load region file

region <- r2dii.data::region_isos

# load in ald   

ald <- tibble::tribble(
  ~name_company,       ~sector, ~technology, ~year, ~production, ~production_unit, ~emission_factor, ~ald_emission_factor_unit, ~plant_location, ~is_ultimate_owner, ~ald_timestamp,
  "company a", "oil and gas",       "gas", 2020L, 2021866.942,             "GJ",               NA,                        NA,            "NG",               TRUE,       "2019Q4",
  "company a", "oil and gas",       "oil", 2020L, 18693705.69,             "GJ",               NA,                        NA,            "NG",               TRUE,       "2019Q4"
)

# load in match file 

match_file <- tibble::tribble(
  ~X1,           ~id_loan, ~id_direct_loantaker, ~name_direct_loantaker, ~id_intermediate_parent_1, ~name_intermediate_parent_1, ~id_ultimate_parent, ~name_ultimate_parent, ~loan_size_outstanding, ~loan_size_outstanding_currency, ~loan_size_credit_limit, ~loan_size_credit_limit_currency, ~sector_classification_system, ~sector_classification_input_type, ~sector_classification_direct_loantaker, ~fi_type, ~flag_project_finance_loan, ~name_project, ~lei_direct_loantaker, ~isin_direct_loantaker, ~id_2dii,             ~level,       ~sector,   ~sector_ald,       ~name,   ~name_ald, ~score,    ~source, ~borderline,
  77L, "099CTLN163510001",                "DL1",            "company a",                        NA,                          NA,               "UP1",           "company a",                    50L,                           "NGN",                    100L,                            "NGN",                       "NAICS",                            "Code",                                 211120L,   "Loan",                       "No",            NA,                    NA,                     NA,    "DL1", "direct_loantaker", "oil and gas", "oil and gas", "company a", "company a",     1L, "loanbook",       FALSE,
  78L, "099CTLN163510001",                "DL1",            "company a",                        NA,                          NA,               "UP1",           "company a",                   100L,                           "NGN",                    200L,                            "NGN",                       "NAICS",                            "Code",                                 211120L,   "Loan",                       "No",            NA,                    NA,                     NA,    "UP1",  "ultimate_parent", "oil and gas", "oil and gas", "company a", "company a",     1L, "loanbook",       FALSE,
  77L, "099CTLN163510002",                "DL1",            "company a",                        NA,                          NA,               "UP1",           "company a",                    20L,                           "NGN",                    250L,                            "NGN",                       "NAICS",                            "Code",                                 211120L,   "Loan",                       "No",            NA,                    NA,                     NA,    "DL1", "direct_loantaker", "oil and gas", "oil and gas", "company a", "company a",     1L, "loanbook",       FALSE,
  78L, "099CTLN163510002",                "DL1",            "company a",                        NA,                          NA,               "UP1",           "company a",                    25L,                           "NGN",                    300L,                            "NGN",                       "NAICS",                            "Code",                                 211120L,   "Loan",                       "No",            NA,                    NA,                     NA,    "UP1",  "ultimate_parent", "oil and gas", "oil and gas", "company a", "company a",     1L, "loanbook",       FALSE
)


# prioritize matches 

lbk_ready <- prioritize(match_file)


# generate company level results 

company_results <- target_market_share(lbk_ready, ald, scenario, region, by_company = TRUE, weight_production = FALSE)


# test expected vs actual 

expected <- ald %>% filter(year == 2020,
                           name_company == "company a")

actual <- company_results %>% filter(year == 2020,
                                     metric == "projected")

identical(actual$production, expected$production)
#> [1] TRUE
```

### PR DESCRIPTION
**Pull request by jdhoffa**
Closes #267
Thanks for flagging the issue @georgeharris2deg 

I elected to go the more restrictive route since there is some internal aggregations and groupings happening, it's impossible to know arbitrarily how to handle any unexpected column. 

This option will prevent the user from even being able to input unexpected columns, even if they want to. Happy to revisit the decision, but I think it's safest for now.

### CODE REVIEW

File: R/target_market_share.R [hunk 1]
```diff
@@ -401,3 +407,49 @@ aggregate_by_loan_id <- function(data) {
     ) %>%
     ungroup()
 }
+
+check_unexpected_columns <- function(data) {
+
+  possible_matched_columns <- c(
```
Comment (maurolepore) [inline R/target_market_share.R:413]: How about `valid_colums`?

File: R/target_market_share.R [hunk 2]
```diff
@@ -401,3 +407,49 @@ aggregate_by_loan_id <- function(data) {
...
+    "sector",
+    "sector_ald",
+    "name",
+    "name_ald",
+    "score",
+    "source",
+    "borderline"
+    )
+
+unexpected_names <- setdiff(names(data), possible_matched_columns)
```
Comment (maurolepore) [inline R/target_market_share.R:444]: How about `invalid_columns`? The word invalid more strongly conveys the program will fail -- as opposed to "unexpected"  (e.g. a present might be unexpected but welcome).

File: tests/testthat/test-target_market_share.R [hunk 3]
```diff
@@ -676,3 +676,19 @@ test_that("for one company with multiple loans of different size, unweighted
 
   expect_equal(projected$production, fake_ald()$production)
 })
+
+test_that("with bad column errors with informative message (#267)", {
```
Comment (maurolepore) [inline tests/testthat/test-target_market_share.R:680]: Can we use "column" (prefer) or "names" not both?

**Review by maurolepore — CHANGES_REQUESTED** [review]
Thanks! I highlighted a few easy wins :-)

File: R/target_market_share.R [hunk 4]
```diff
@@ -401,3 +407,49 @@ aggregate_by_loan_id <- function(data) {
...
+
+  if (length(unexpected_names) != 0) {
+    abort(
+      glue("Loanbook has unexpected names: `{unexpected_names}`."),
```
Comment (maurolepore) [inline R/target_market_share.R:448]: I haven't yet fully understood how an unexpected column caused the problem -- I plan to explore a bit. But this solution is likely to break existing user's code, so if we go this route we may need to help users a bit more. Maybe add a hint to show the code a user would run to remove invalid columns?

Comment (jdhoffa) [reply R/target_market_share.R:448]: I think the answer to this question actually lies in the open PR #270
I made a hasty solution, where I aggregated by grouping by all but a few columns (using `group_by_at()` and `setdiff()`) without thinking about the downstream implications of such a decision. In hindsight, this was actually a pretty huge mistake IMO.

File: R/target_market_share.R [hunk 5]
```diff
@@ -401,3 +407,49 @@ aggregate_by_loan_id <- function(data) {
     ) %>%
     ungroup()
 }
+
+check_unexpected_columns <- function(data) {
```
Comment (maurolepore) [inline R/target_market_share.R:411]: To make this helper more reusable I suggest passing `valid_columns` as an argument. This way the useful logic is not mixed with the low-level detail of which specific columns are valid.

File: tests/testthat/test-target_market_share.R (hunk 3 above)
Comment (jdhoffa) [reply tests/testthat/test-target_market_share.R:680]: Sure, although we have an old set of tests with the class `missing_names`, so likely we should fix this as well. Not sure if that should happen in this PR

Comment (maurolepore) [reply tests/testthat/test-target_market_share.R:680]: I'm happy to get that refactoring here. To me, fighting rot is important and doing it here may reduce the friction.

**Review by maurolepore — APPROVED** [review]
LGTM. Nit:
* Rename whatever seems necessary.
* Write a hint so users know what to do when their data throws an error with this pickier approach.
