### PR TITLE
Set `technology_share` to 0 for companies with zero initial sectoral production

### LINKED ISSUE #306: `target_market_share` passes an unhelpful internal error when a company has 0 production and `NA` emission_factors
In `target_market_share`, there is a downstream function `add_technology_share` which calculates the share of each technology, per company, year and sector. If, for some year, sector, company, the total production is 0, then the `add_technology_share` function will divide by 0, causing an error. 

We should likely add a check higher in the callstack to ensure we account for this situation. 

Thanks @EvgenyPetrovsky for flagging this, and drafting the useful reprex below: 

---

Brief description of the problem

``` r
library(magrittr)
require(r2dii.data)
#> Loading required package: r2dii.data
require(r2dii.match)
#> Loading required package: r2dii.match
require(r2dii.analysis)
#> Loading required package: r2dii.analysis

lbk_demo <- r2dii.data::loanbook_demo
ald_demo <- r2dii.data::ald_demo
scn_demo <- r2dii.data::scenario_demo_2020
rgn_demo <- r2dii.data::region_isos_demo

# matching
lbk_matched <- r2dii.match::match_name(loanbook = lbk_demo, ald = ald_demo) %>% 
  r2dii.match::prioritize()

# selecting first name from matched ald data and taking some year
one_name <- lbk_matched$name_ald %>% 
  unique() %>% 
  (function(x) x[!is.na(x)]) %>% 
  head(1)

one_year <- 2020

# breaking data across all technologies for one selected ald name_company and year
ald_broken <- ald_demo

ald_broken[ald_broken$name_company == one_name & ald_broken$year == one_year, "emission_factor"] <- NA

ald_broken[ald_broken$name_company == one_name & ald_broken$year == one_year, "production"] <- 0

# running analysis
target_market_share <- r2dii.analysis::target_market_share(
  
  data = lbk_matched, 
  
  ald = ald_broken, 
  
  scenario = scn_demo, 
  
  region_isos = rgn_demo,
  
  by_company = FALSE)
#> Error: Column `technology_share` must not contain any `NA`s.
```

<sup>Created on 2021-06-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### PR DESCRIPTION
**Pull request by jdhoffa**
This PR is a sparse implementation of @Antoine-Lalechere's fix to set `technology_share` values to `0` should they have no initial sectoral production (#348). 

Closes #306 
Closes [ADO 876](https://dev.azure.com/2DegreesInvesting/2DegreesInvesting/_workitems/edit/876)

### CODE REVIEW

File: R/summarize_weighted_production.R [hunk 1]
```diff
@@ -282,7 +286,11 @@ add_technology_share_target <- function(data) {
       .data$name_ald,
       .data$region
     ) %>%
-    mutate(technology_share_target = .data$production_target / sum(.data$production_target)) %>%
+    mutate(
+      .x = sum(.data$production_target),
+      technology_share_target = ifelse(.data$.x == 0, 0, .data$production_target / .data$.x),
+      .x = NULL
+    ) %>%
```
Comment (maurolepore) [inline R/summarize_weighted_production.R:293]: Just an idea, I wonder if we could extract this pattern into a wrapper around `mutate()` with a new `.x` argument that will be automatically destroyed  after use. Nothing to take action but to spark thoughts.

File: R/target_market_share.R [hunk 2]
```diff
@@ -402,8 +402,8 @@ calculate_ald_benchmark <- function(ald, region_isos, by_company) {
       .data$sector, .data$year, .data$region, .data$source
     ) %>%
     mutate(
-      .x = .data$production,
-      technology_share = .data$.x / sum(.data$.x),
+      .x = sum(.data$production),
```
Comment (maurolepore) [inline R/target_market_share.R:405]: Every time I see sum I think of `na.rm`. Maybe `NA`s are handled above but one way to remove the worry is to either add `na.rm = TRUE` explicitely (if it corresponds) or maybe implement `add()` as a wrapper of `sum()` that defaults to `na.rm = TRUE`.

File: R/target_market_share.R [hunk 3]
```diff
@@ -437,11 +437,23 @@ reweight_technology_share <- function(data, ...) {
...
+      .sum_x = sum(.data$.x),
       .y = .data$weighted_technology_share_target,
-      weighted_technology_share = .data$.x / sum(.data$.x),
-      weighted_technology_share_target = .data$.y / sum(.data$.y),
+      .sum_y = sum(.data$.y),
+      weighted_technology_share = ifelse(
+        .data$.sum_x == 0,
+        0,
+        .data$.x / .data$.sum_x
+        ),
```
Comment (maurolepore) [inline R/target_market_share.R:447]: Nit: Is it worth taking so much vertical screen-real-state?

File: tests/testthat/test-target_market_share.R [hunk 4]
```diff
@@ -1143,3 +1143,34 @@ test_that("`target_market_share` outputs only positive values of `production`(#3
 
   expect_false(any(out$production < 0))
 })
+
+test_that("`target_market_share` outputs as expected for companies with 0 initial sectoral production (#306)", {
```
Comment (maurolepore) [inline tests/testthat/test-target_market_share.R:1147]: Nit: Do we need to wrap at 80 chars?

**Review by maurolepore — APPROVED** [review]
LGTM. The tests make me comfortable that the code does what's intended to do. My comments are all nit.

File: R/summarize_weighted_production.R (hunk 1 above)
Comment (jdhoffa) [reply R/summarize_weighted_production.R:293]: Ya this seems like an interesting idea. Would have to think carefully about what to call the new function

File: R/target_market_share.R (hunk 3 above)
Comment (jdhoffa) [reply R/target_market_share.R]: Nope! You are right, this was silly.

File: R/target_market_share.R (hunk 2 above)
Comment (jdhoffa) [reply R/target_market_share.R:405]: I am a little hesitant to pass `na.rm = TRUE` to calls to `sum()`, my reasoning is as follows: 
#306 was flagged because `target_market_share` passing an error, due to some `NA` that was added internally. The input data had no `NA`s, so it was something in the code that was introducing the `NA`s. 

These `NA`s were not expected, so this error forced us to recognize the problem and address it. 

If we had passed `na.rm = TRUE`, I imagine this bug would have persisted silently, and we likely would have taken a lot longer to learn about it.

File: tests/testthat/test-target_market_share.R (hunk 4 above)
Comment (jdhoffa) [reply tests/testthat/test-target_market_share.R]: Done
